spring.application.name=scraper-engine
# Hide the Spring Boot startup ASCII art
spring.main.banner-mode=off

# Suppress all routine INFO spam from Spring and the web drivers
logging.level.root=WARN
logging.level.org.springframework=ERROR
logging.level.com.microsoft.playwright=ERROR

# Ensure your application's severe errors are printed
logging.level.com.jcf.scraper_engine=WARN